In [1]:
from dataclasses import dataclass, field
from datetime import datetime, date
import gymnasium as gym
from gymnasium import spaces

import numpy as np
from scipy.stats import norm

In [12]:
action_space = spaces.MultiBinary(12)
action_space.sample()

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1], dtype=int8)

In [4]:


action_space = spaces.MultiDiscrete([3] * 12)
action_space.sample()

array([0, 1, 2, 2, 0, 2, 0, 1, 2, 1, 1, 1])

In [59]:
action_space = spaces.MultiDiscrete([3] * 10 + [2] * 2)
action_space.sample()

array([1, 0, 2, 1, 0, 0, 2, 0, 0, 0, 1, 0])